name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Install dependencies
      run: npm ci

    - name: StandardJS and Prettier
      run: npx eslint ./src/**/*.js

    - name: Stylelint
      run: npx stylelint "./source/**/*.css"

    - name: HTMLHint
      run: npx htmlhint "./source/**/*.html"

    - name: Jest (optional)
      id: jest
      run: npx jest || echo '::set-output name=status::failure'

    - name: JSDoc
      run: npx jsdoc -c jsdoc.config.json

    - name: CodeClimate
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
        ./cc-test-reporter after-build --exit-code ${{ steps.jest.outputs.status == 'failure' && 1 || 0 }}
