name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      name: List the state of node modules
      continue-on-error: true
      run: npm list

    - name: Install dependencies
      run: npm install

    - name: ESLint and Prettier
      run: |
        npx eslint --fix ./source/**/*.js
        npx prettier --write "./source/**/*.{js,css,html}"

    - name: Stylelint
      run: npx stylelint --fix "./source/**/*.css"

    - name: HTMLHint
      run: npx htmlhint --config .htmlhintrc "./source/**/*.html"

    - name: Jest
      id: jest
      run: npm test

    - name: JSDoc
      run: npx jsdoc -c jsdoc.config.json

    - name: Check for changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git diff --quiet || (git add -A && git commit -m 'Automatically fix style issues and add new JSDocs' && git push https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git)

