name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Install dependencies
      run: npm ci

    - name: ESLint and Prettier
      run: |
        npx eslint --fix ./source/**/*.js
        npx prettier --write "./source/**/*.{js,css,html}"

    - name: Stylelint
      run: npx stylelint --fix "./source/**/*.css"

    - name: HTMLHint
      run: npx htmlhint --config .htmlhintrc "./source/**/*.html"

    - name: Jest (optional)
      id: jest
      run: npx jest || echo '::set-output name=status::failure'

    - name: JSDoc
      run: npx jsdoc -c jsdoc.config.json

    - name: Check for changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git diff --quiet || (git add -A && git commit -m 'Automatically fix style issues and add new JSDocs' && git push https://${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git)

